# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3068904c7cff17a130f645e47da2e260df198b45ef41ea3620b101f8aa0be25c1cfe27fe5ef023582b22291f2f86dd6febd2e58218f71634da2c6e21b611398e

test:
  secret_key_base: fb31546822210f1742924ed2bd277eb6be9c03f17b4c583a62a7f8a2188b4571deef977985dd1cf954477b944fa75c7d8032fc5436e3ed2d76f416b2ad263024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
